// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZr6sw2WKRwctTJMHehT86xyws_fu1kf0',
    appId: '1:628858184888:web:a4caffaab8b3a18c6c004d',
    messagingSenderId: '628858184888',
    projectId: 'prashantecommerceapp',
    authDomain: 'prashantecommerceapp.firebaseapp.com',
    storageBucket: 'prashantecommerceapp.appspot.com',
    measurementId: 'G-4S6P4W4370',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5O8YiqAQCpIjYMn9BMnjrWIJbpLugyRk',
    appId: '1:628858184888:android:0f25c5a0b818b5ae6c004d',
    messagingSenderId: '628858184888',
    projectId: 'prashantecommerceapp',
    storageBucket: 'prashantecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJLfW2EQuLkI78LfKNR8JEQuft2J40Gc',
    appId: '1:628858184888:ios:44f909e1673892086c004d',
    messagingSenderId: '628858184888',
    projectId: 'prashantecommerceapp',
    storageBucket: 'prashantecommerceapp.appspot.com',
    androidClientId: '628858184888-81ed8g734912od9li4hnufd3a8tfm14g.apps.googleusercontent.com',
    iosClientId: '628858184888-sos61npfffpv5ntjla3g35pos3ociidl.apps.googleusercontent.com',
    iosBundleId: 'com.example.prashantECommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJLfW2EQuLkI78LfKNR8JEQuft2J40Gc',
    appId: '1:628858184888:ios:44f909e1673892086c004d',
    messagingSenderId: '628858184888',
    projectId: 'prashantecommerceapp',
    storageBucket: 'prashantecommerceapp.appspot.com',
    androidClientId: '628858184888-81ed8g734912od9li4hnufd3a8tfm14g.apps.googleusercontent.com',
    iosClientId: '628858184888-sos61npfffpv5ntjla3g35pos3ociidl.apps.googleusercontent.com',
    iosBundleId: 'com.example.prashantECommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZr6sw2WKRwctTJMHehT86xyws_fu1kf0',
    appId: '1:628858184888:web:6e32f1e97f8d43156c004d',
    messagingSenderId: '628858184888',
    projectId: 'prashantecommerceapp',
    authDomain: 'prashantecommerceapp.firebaseapp.com',
    storageBucket: 'prashantecommerceapp.appspot.com',
    measurementId: 'G-C9CJG5K28X',
  );

}